### ISSUE TITLE
volume permissions

### ISSUE THREAD

**Issue by leier69** [docker/for-linux#1038]
Hi, So I have something I dont understand about docker volumes and it might be an issue

```
version: "3.8"

networks:
  default:
    name: my-net

volumes:
  influxdb-data:

services:
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    user: 988:982
    expose:
      - 8086
    volumes:
      - influxdb-data:/var/lib/influxdb
  #   - /etc/influxdb:/etc/influxdb
    environment:
      - "INFLUXDB_READ_USER=grafana"
      - "INFLUXDB_READ_USER_PASSWORD=${INFLUXDB_READ_USER_PASSWORD}"
    restart: always
```

Im using the following docker compose file and running influx as a local influx user and group (988:982). But, my volume has wrong permissions and are set to `systemd-coredump input` instead of `988:982` as they should have been

```
sudo ls -lah /var/lib/docker/volumes/tig-stack_influxdb-data/_data
total 0
drwxr-xr-x. 2 systemd-coredump input  6 Apr 12 09:56 .
drwxr-xr-x. 3 root             root  19 Jun  9 03:43 ..
```

I should be able to use docker volumes as apposed to using mount binds. Please help or confirm if this needs to be added.
