### ISSUE TITLE
Unhealthy containers cant be stopped

### ISSUE THREAD

**Issue by SeaLife** [docker/for-linux#1097]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

The Healthcheck of my containers are working fine and containers
with healthcheck in the state of "unhealthy" will stop properly when stopped.

### Actual behavior

The healthchecks are working fine for some time but will start to timeout later on.
A container in a unhealthy state can't be stopped by `docker stop`.
Forcefully removing the container works but the container is not fully removed from the system (the container remains member of assigned networks, ...)

### Steps to reproduce the behavior

We'r running on arch-linux with the latest docker version (see below) and the latest docker-compose version (see below).
I attached a docker-compose stack we'r encountering this issue with (especially the clamav service, as this service got a healthcheck, we removed all other custom healthchecks due to this issue)

**Output of `docker version`:**

```
Client:
 Version:           19.03.12-ce
 API version:       1.40
 Go version:        go1.14.5
 Git commit:        48a66213fe
 Built:             Sat Jul 18 01:33:21 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.12-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.14.5
  Git commit:       48a66213fe
  Built:            Sat Jul 18 01:32:59 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.0.m
  GitCommit:        09814d48d50816305a8e6c1a4ae3e2bcc4ba725a.m
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 11
  Running: 11
  Paused: 0
  Stopped: 0
 Images: 34
 Server Version: 19.03.12-ce
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 09814d48d50816305a8e6c1a4ae3e2bcc4ba725a.m
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.8.5-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 62.6GiB
 Name: seoka.dev
 ID: O6GQ:737Q:5V2Y:DRKN:2Q2N:F25C:353H:RNF2:LUCV:U7Q3:6XZM:BTZV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: seoka
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

| What | Version |
| ------ | -------- |
| OS | Arch Linux |
| Kernel | `5.8.5-arch1-1 #1 SMP PREEMPT Thu, 27 Aug 2020 18:53:02 +0000 x86_64 GNU/Linux` |
| runc | 1.0.0-rc92 | 
| containerd | v1.4.0.m 09814d48d50816305a8e6c1a4ae3e2bcc4ba725a.m |
| docker-compose | 1.26.2 |

The Docker-Compose Stack we used:

```
version: '3.4'
services:
  nextcloud:
    image: nextcloud
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.${HOSTNAME}`)"
      - "traefik.http.routers.nextcloud.entrypoints=https,http"
      - "traefik.http.routers.nextcloud.tls.certresolver=letsencrypt"
    networks:
      - web
      - internal
      - db
    tmpfs:
      - /tmp
    volumes:
      - "/srv/docker/nextcloud/data:/var/www/html/data"
      - "/srv/docker/nextcloud/config:/var/www/html/config"
      - "/srv/docker/nextcloud/custom_apps:/var/www/html/custom_apps"
      - "/srv/docker/nextcloud/themes:/var/www/html/themes"
      - "/dev/urandom:/dev/urandom:ro"
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped

  clamav:
    image: mkodockx/docker-clamav
    labels:
      - "traefik.enable=false"
    networks:
      - internal
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped

  draw_io:
    image: jonberenguer/draw.io
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drawio.rule=Host(`drawio.backend.${HOSTNAME}`)"
      - "traefik.http.routers.drawio.entrypoints=https,http"
      - "traefik.http.routers.drawio.tls.certresolver=letsencrypt"
      - "traefik.http.routers.drawio.middlewares=drawio"
      - "traefik.http.middlewares.drawio.addprefix.prefix=/draw.io/war"
      - "traefik.http.services.drawio.loadbalancer.server.port=80"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    hostname: drawio.backend.${HOSTNAME}
    networks:
      - web
      - internal
    restart: unless-stopped

  onlyoffice:
    image: onlyoffice/documentserver
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.onlyoffice.rule=Host(`onlyoffice.backend.${HOSTNAME}`)"
      - "traefik.http.routers.onlyoffice.entrypoints=https,http"
      - "traefik.http.routers.onlyoffice.tls.certresolver=letsencrypt"
      - "traefik.http.routers.onlyoffice.middlewares=sslheader"
      - "traefik.http.services.onlyoffice.loadbalancer.server.port=80"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
    networks:
      - web
      - internal
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped

  collabora:
    image: collabora/code
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.collabora.rule=Host(`collabora.backend.${HOSTNAME}`)"
      - "traefik.http.routers.collabora.entrypoints=https,http"
      - "traefik.http.routers.collabora.tls.certresolver=letsencrypt"
      - "traefik.http.routers.collabora.middlewares=sslheader"
      - "traefik.http.services.collabora.loadbalancer.server.port=9980"
      - "traefik.http.services.collabora.loadbalancer.sticky=true"
      - "traefik.http.services.collabora.loadbalancer.sticky.cookie.secure=true"
    networks:
      - web
      - internal
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped
    cap_add:
      - MKNOD
    environment:
      - DONT_GEN_SSL_CERT=true
      - domain=cloud\\.${HOSTNAME}
      - username=test
      - "password=XXXXXX"
      - server_name=collabora.backend.${HOSTNAME}
      - dictionaries=de_DE en_GB en_US
      - "extra_params=--o:ssl.enable=false --o:ssl.termination=true"


networks:
  internal:
    driver: bridge
  db:
    external:
      name: db
  web:
    external:
      name: web
```

HINT: The `clamav` service comes with a built-in healthcheck, which fails after some hours on this system.

`docker inspect nextcloud_clamav_1`:

https://pastebin.com/Qd0qRPFz (its quite big)
