### ISSUE TITLE
LimitMEMLOCK does't work on docker 19.03.12/ubuntu20.04 and centos 7.8

### ISSUE THREAD

**Issue by godisboy0** [docker/for-linux#1099]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior

I am trying to deploy an es cluster with docker swarm.
I want to lock memory as es document suggested.

### Actual behavior
before I post this issue, I have done a lot search work. this is what I've done
1. add `LimitMEMLOCK=infinity` to `/lib/systemd/system/docker.service`, then reboot.
2. I specified 'bootstrap.memory_lock=true' in docker-compose.yml as below
3. `docker stack deploy es -compose-file=docker-compose.yml`.
two things happend:
1. ulimits are ignored by docker stack
2. ES failed to start because It can't lock enough memory
then I run `docker run --rm elasticsearch:7.2.0 /bin/bash -c 'ulimit -Ha'`
only to get:
```
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 62445
max locked memory       (kbytes, -l) 64   # still 64 here
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```
### Steps to reproduce the behavior

this is my docker-compose.yml
```yml
version: "3.7"

services:
  es1:
    image: elasticsearch:7.2.0
    healthcheck:
      test: curl -fs http://localhost:9200/_cat/health || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 45s
    configs:
      - source: es-master1
        target: /usr/share/elasticsearch/config/elasticsearch.yml
      - source: jvm-options
        target: /usr/share/elasticsearch/config/jvm.options
    networks:
      - es-net
    volumes:
      - /root/es/data:/usr/share/elasticsearch/data
      - /root/es/logs:/usr/share/elasticsearch/logs
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      placement:
        constraints: [ node.hostname==es1 ]
      resources:
        limits:
          memory: 700M # 测试数量

  es2:
    image: elasticsearch:7.2.0
    healthcheck:
      test: curl -fs http://localhost:9200/_cat/health || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 45s
    configs:
      - source: es-master2
        target: /usr/share/elasticsearch/config/elasticsearch.yml
      - source: jvm-options
        target: /usr/share/elasticsearch/config/jvm.options
    networks:
      - es-net
    volumes:
      - /root/es/data:/usr/share/elasticsearch/data
      - /root/es/logs:/usr/share/elasticsearch/logs
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      placement:
        constraints: [ node.hostname==es2 ]
      resources:
        limits:
          memory: 700M

  es3:
    image: elasticsearch:7.2.0
    healthcheck:
      test: curl -fs http://localhost:9200/_cat/health || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 45s
    configs:
      - source: es-master3
        target: /usr/share/elasticsearch/config/elasticsearch.yml
      - source: jvm-options
        target: /usr/share/elasticsearch/config/jvm.options
    networks:
      - es-net
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /root/es/data:/usr/share/elasticsearch/data
      - /root/es/logs:/usr/share/elasticsearch/logs
    deploy:
      placement:
        constraints: [ node.hostname==es3 ]
      resources:
        limits:
          memory: 700M

  kibana:
    image: kibana:7.2.0
    environment:
      - "ELASTICSEARCH_URL=http://es1:9200"
    networks:
      - es-net
    ports:
      - "5601:5601"
    deploy:
      placement:
        constraints: [ node.hostname==es1 ]
      mode: replicated
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3

networks:
  es-net:
    driver: overlay
    attachable: true
    name: es-net

# volumes:
#   esmaster1:
#   esmaster2:
#   esmaster3:

configs:
  es-master1:
    name: es-master1
    file: es-config/es1.yml
  es-master2:
    name: es-master2
    file: es-config/es2.yml
  es-master3:
    name: es-master3
    file: es-config/es3.yml
  jvm-options:
    name: jvm-options
    file: es-config/jvm.options
```
here is es1/2/3.yml
```yml
bootstrap.memory_lock: true
discovery.zen.minimum_master_nodes: 2
discovery.zen.ping.unicast.hosts: es1, es2, es3
discovery.zen.ping_timeout: 5s
discovery.zen.commit_timeout: 5s
node.master: true
node.data: true
node.ingest: false
node.name: es1   # es2 for es2.yml, es3 for es3.yml
cluster.name: "docker-swarm-cluster"
network.host: 0.0.0.0
action.destructive_requires_name: true
cluster.initial_master_nodes: es1,es2,es3
```
here is jvm.options.
```
-Xms512M
-Xmx512M
```

what I wonder is, why LimitMEMLOCK didn't work.
should I just turn on vm.swappiness=-1 and forget memlock?

**Output of `docker version`:**

```
Docker version 19.03.12, build 48a66213fe
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-45-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.3GiB
 Name: mt-ThinkPad-T14-Gen-1
 ID: H3CW:NZJU:UIDA:LAUJ:YQB4:RLTU:OETR:UABV:PHOB:A5WG:6E6P:2ZSU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  http://hub-mirror.c.163.com/
  https://registry.docker-cn.com/
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
ubuntu 20.04
centos 7.8
