### ISSUE TITLE
Unable to access host port from the docker stack deploy container

### ISSUE THREAD

**Issue by yog27ray** [docker/for-linux#1249]
I cannot access the host port from the service container in the Linux environment but the same setup works fine in mac os.

docker-compose.yml
```
version: "3.8"

services:
  analytics:
    image: '##imageName##'
    environment:
      SERVER_2_URL: "http://host.docker.internal:9001"
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

```

command
```
docker stack deploy -c docker-compose.yml test --with-registry-auth
```

The above configuration works well in macOS Big Sur (11.3.1) and Docker version 20.10.5, build 55c4c88. But the same configuration is unable to access the host machine port 9001 in Ubuntu 18.04.5 LTS and Docker version 20.10.2, build 20.10.2-0ubuntu1~18.04.2.

I have also tried "http://gateway.docker.internal:9001" instead of "http://host.docker.internal:9001" but still, I was not able to access port 9001.
