### ISSUE TITLE
docker-ce 25.0.0 error when stopping and re-creating container

### ISSUE THREAD

**Issue by farces** [docker/for-linux#1481]
Since updating to the latest docker-ce build on Ubuntu, stopping and re-creating a container in quick succession throws the following error:

(logs from Watchtower)
```
time="2024-01-22T00:07:24Z" level=info msg="Found new jwilder/nginx-proxy:latest image (c55e0435bcab)"
time="2024-01-22T00:07:25Z" level=info msg="Stopping /nginx-proxy (b23e7978ed10) with SIGTERM"
time="2024-01-22T00:07:35Z" level=info msg="Creating /nginx-proxy"
time="2024-01-22T00:07:35Z" level=error msg="Error response from daemon: invalid config for network bridge: invalid endpoint settings:\nnetwork-scoped alias is supported only for containers in user defined networks"
time="2024-01-22T00:07:35Z" level=info msg="Session done" Failed=1 Scanned=7 Updated=0 notify=no
```

Manually starting the container after this with no further modifications succeeds. Testing quick re-creation of a container in Portainer results in the same error occasionally. I haven't tested enough to identify whether there's a specific threshold of time between stopping a container and re-creating it where this issue presents itself.

This hasn't happened previously on any docker-ce version on this same system, over the course of several years. This particular issue has also been raised in the Watchtower project as [Issue 1906](https://github.com/containrrr/watchtower/issues/1906), however based on users having this symptom with Portainer as well it looks more likely to be an external issue.

The container from my logs was created using docker-compose.

Docker version:
```
user@localhost:~/nginx-proxy$ docker version
Client: Docker Engine - Community
 Version:           25.0.0
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        e758fe5
 Built:             Thu Jan 18 17:09:49 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.0
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       615dfdf
  Built:            Thu Jan 18 17:09:49 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.27
  GitCommit:        a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc:
  Version:          1.1.11
  GitCommit:        v1.1.11-0-g4bccb38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by akerouanton** [comment]
Hi @farces, since v25.0 container's networking config is validated when a container is created, instead of being done when a container is started. This was done to provide early feedback when an invalid config is found.

I'm a bit puzzled by the claim that: 1. it happens only when re-creating in quick succession; and 2. it worked properly prior to v25. About claim 1., you mentioned you're able to start affected containers by hand. Could you paste the output of `docker inspect` for such a container please?

Also, could you enable debug logs as documented here: https://docs.docker.com/config/daemon/logs/#enable-debugging, and provide the log line "form data ..." that comes right after the log line `Calling POST /v1.44/containers/create` for a container that faces the validation error? And finally, could you provide the original `docker run` or `docker create` command, or compose file used to create the original container please?

**Comment by MrEAlderson** [comment]
Not sure whether that's helpful or not, however whenever Watchtower would do its thing, the container that is supposed to get updated turns into a weird state. Portainer would show networks (that I added myself before the update) for that updated container that practically don't exist. Practically, because I can fix it by going into the console and manually connecting all listed on Portainer using "docker network connect". Docker doesn't throw an error that the given network is already connected

**Comment by akerouanton** [comment]
That seems to indicate something is broken in Watchtower itself and that this issue only surfaces now as we're more stringent on what we accept during `POST /containers/create`. I'd recommend to deep dive into Watchtower logs and code (and docker debug logs) to make sure the endpoint settings aren't totally off the mark.

**Comment by farces** [comment]
> Hi @farces, since v25.0 container's networking config is validated when a container is created, instead of being done when a container is started. This was done to provide early feedback when an invalid config is found.
> 
> I'm a bit puzzled by the claim that: 1. it happens only when re-creating in quick succession; and 2. it worked properly prior to v25. About claim 1., you mentioned you're able to start affected containers by hand. Could you paste the output of `docker inspect` for such a container please?

Same honestly, looking at watchtowers code it's doing more than I thought it'd need to do, and my tests were using watchtower vs. manually performing the same steps - missing a few it turns out.

Here's the docker-compose for an impacted container:
```yaml
version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - ./.vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: bridge
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    restart: always
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
```
There's nothing special about the networking, it's just using the system bridge network.

The docker inspect output from the container started by hand after seeing the error via watchtower, Networks section only:
```yaml
"Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "9ed32c210916"
                    ],
                    "MacAddress": "02:42:ac:11:00:05",
                    "NetworkID": "7d7096cd9c74b1bf36c8edb4a4c1decaf3adfd79ca880dd83082fc4e5889b7e6",
                    "EndpointID": "c0b6dfc9b974e35111519b367776d6fc8162546a710800c758ec0171f46135e4",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.5",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "DriverOpts": null,
                    "DNSNames": null
                }
            }
```
The only alias listed is the container ID, and this is for a running container.

I'll enable debug logging and see if I can get anything from Watchtower as well. But it's looking more like this is some oddness with watchtower (and potentially portainer) that will need to be fixed up for 25.0.
