### ISSUE TITLE
ulimits option ignored in docker compose

### ISSUE THREAD

**Issue by pedropapa** [docker/for-linux#152]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
Docker compose should read the yaml file and use `ulimits` property of services to set up service limits.

### Actual behavior
After running `docker stack deploy -c /path/to/myfile.yml mystack`, I get the message `Ignoring unsupported options: ulimits`

### Steps to reproduce the behavior
**yaml file**:
1. Create a file called `es.yml` with the following content:

```
version: "3.4"

services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.port: "9200"
        traefik.backend: "elasticsearch1"
        traefik.frontend.rule: "Host:elasticsearch.theappchefs.com"
        traefik.frontend.passHostHeader: 'true'
        traefik.docker.network: "proxy"
      resources:
        limits:
          memory: 2g
    ports:
      - 9200:9200
    networks:
      - proxy
      - mersen

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.3
    environment:
      SERVER_NAME: kibana.theappchefs.com
      ELASTICSEARCH_URL: elasticsearch.theappchefs.com
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.port: "5601"
        traefik.backend: "kibana"
        traefik.frontend.rule: "Host:kibana.theappchefs.com"
        traefik.frontend.passHostHeader: 'true'
        traefik.docker.network: "proxy"
    ports:
      - 5601:5601
    networks:
      - proxy
      - mersen

networks:
  proxy:
     external: true
  mersen:
     external:
      name: mersen
  elasticsearch:
     external:
      name: mersen
```
2. Create a new docker stack with the following command: `docker stack deploy -c /data/docker-stack/api.yml es`

**Output of `docker version`:**

```
Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:04:16 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:02:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 46
 Running: 1
 Paused: 0
 Stopped: 45
Images: 5
Server Version: 17.10.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 124
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: zarzb8wiij4kc4vkib5x3962x
 Is Manager: true
 ClusterID: uefo4l658j2j4krb8xw9r1juj
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 45.55.172.96
 Manager Addresses:
  45.55.172.96:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-98-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.3MiB
Name: docker-1gb-productrecognition
ID: U32L:SF2X:KQZW:CBUL:TXYE:IHSC:WRB5:WUDQ:TJI7:UTGC:VKK5:WVZF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

I'm using Docker under a DigitalOcean Droplet running Ubuntu, here's the `uname -mrs` output:

```
Linux 4.4.0-98-generic x86_64
```
