### ISSUE TITLE
docker network create with opts encrypted, nodes fail to communicate

### ISSUE THREAD

**Issue by dalu** [docker/for-linux#168]
* [x] This is a bug report
* [x] I searched existing issues before opening this one

### Expected behavior

http://94.130.186.54:8080
reads "connected"
http://94.130.186.54:8081
reads "connected"
http://94.130.186.53:8082
reads "connected"

### Actual behavior

2 out of 3 nodes work
try it yourself
http://94.130.186.54:8080
reads "connected"
http://94.130.186.54:8081
reads "not connected"
http://94.130.186.53:8082
reads "connected"

### Steps to reproduce the behavior

have 3 node docker swarm cluster
with both one ipv4 and ipv6 public routable address
and the following files on master node

dgz.yml
```
version: "3.4"
volumes:
  dgdz1:
    driver: local
  dgdz2:
    driver: local
  dgdz3:
    driver: local
networks:
  default:
    driver: overlay
    driver_opts:
      encrypted: ""
services:
  dgz1:
    image: dgraph/dgraph:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1G
    networks:
      - default
    volumes:
      - "dgdz1:/dgraph"
    command: dgraph zero --bindall=true --my=dgz1:7080 --idx=1 --replicas=3 
  dgz2:
    image: dgraph/dgraph:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1G
    networks:
      - default
    volumes:
      - "dgdz2:/dgraph"
    command: dgraph zero --bindall=true --my=dgz2:7080 --idx=2 --replicas=3 --peer dgz1:7080
  dgz3:
    image: dgraph/dgraph:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1G
    networks:
      - default
    volumes:
      - "dgdz3:/dgraph"
    command: dgraph zero --bindall=true --my=dgz3:7080 --idx=3 --replicas=3 --peer dgz1:7080
```

dgs.yml
```
version: "3.4"
volumes:
  dgds1:
    driver: local
  dgds2:
    driver: local
  dgds3:
    driver: local
networks:
  default:
    driver: overlay
    driver_opts:
      encrypted: ""
services:
  dgs1:
    image: dgraph/dgraph:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 2G
    ports:
      - "8080:8080"
      - "9080:9080"
    networks:
      - default
    volumes:
      - "dgds1:/dgraph"
    command: dgraph server --bindall=true --my=dgs1:7080 --zero=dgz1:7080 --memory_mb=2048
  dgs2:
    image: dgraph/dgraph:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 2G
    ports:
      - "8081:8081"
      - "9081:9081"
    networks:
      - default
    volumes:
      - "dgds2:/dgraph"
    command: dgraph server --bindall=true --my=dgs2:7081 --zero=dgz2:7080 --memory_mb=2048 --port_offset=1
  dgs3:
    image: dgraph/dgraph:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 2G
    ports:
      - "8082:8082"
      - "9082:9082"
    networks:
      - default
    volumes:
      - "dgds3:/dgraph"
    command: dgraph server --bindall=true --my=dgs3:7082 --zero=dgz3:7080 --memory_mb=2048 --port_offset=2
```

then

`docker stack deploy -c dgz.yml dg`
and
`docker stack deploy -c dgs.yml dg`

note the network option encrypted being set

name Anton a bitchin' Bachin and buy him an US flag

5. profit

**Output of `docker version`:**

```
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:17 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:43:42 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 1y5jvo48r51f1efej9os0q4ky
 Is Manager: true
 ClusterID: kj86hqy9qtztyej4mw69lshs9
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 94.130.186.54
 Manager Addresses:
  94.130.186.54:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.13.13-200.fc26.x86_64
Operating System: Fedora 26 (Twenty Six)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.763GiB
Name: n1.selftls.com
ID: X2DY:N3IJ:DWYY:OYCY:USRQ:O24D:5PKJ:FW3H:BFQR:ORMW:3WDS:BYW7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

3 nodes on Hetzner Cloud test
1 node each of
2 vcpu
4GB RAM
40GB SSD

docker swarm via ipv4
docker swarm via ipv6 leads to networking notworking (pun intended)

virgin fedora 26
selinux disabled
iptables empty except for rules created by docker
aka no firewall

same behaviour also happened with a 3 node cockroachdb cluster and you can follow the setup there
https://www.cockroachlabs.com/docs/stable/orchestrate-cockroachdb-with-docker-swarm-insecure.html

except that you write
`docker network create --driver overlay --attachable cockroachdb --opts encrypted`
instead of
`docker network create --driver overlay --attachable cockroachdb`

2 out of 3 cockroach nodes will not be able to join the cluster
likewise 2 out of 3 dgraph nodes will not be able to join the cluster

**NOTE** This IP/Port combination will only be available until 30.11.2017 when the Hetzner Cloud testing ends
