### ISSUE TITLE
Wrong source IP from container with host_binding_ipv4 in a 2 IP host with 1 NIC

### ISSUE THREAD

**Issue by loblab** [docker/for-linux#296]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior

The source IP address should be IP2

### Actual behavior

The source IP address is IP1

### Steps to reproduce the behavior

1. A Linux docker host with 1 NIC, IP address is IP1
2. Bind IP2 to the NIC

```
$ sudo ip addr add IP2/24 dev eth0

$ ip addr
...
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether REDACTED brd ff:ff:ff:ff:ff:ff
    inet IP1/24 brd REDACTED scope global eth0
       valid_lft forever preferred_lft forever
    inet IP2/24 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet6 REDACTED/64 scope link 
       valid_lft forever preferred_lft forever
```
3. Network settings in docker-compose.yml

```
version: "3.0"

networks:
    default:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.host_binding_ipv4: IP1
        ipam:
            driver: default
            config:
                - subnet: NETWORK1/24

    another:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.host_binding_ipv4: IP2
        ipam:
            driver: default
            config:
                - subnet: NETWORK2/24
```

4. The container SERVER1 is in network "default", SERVER2 in network "another"

5. Run Wireshark on TARGET to capture ICMP packets

6. ping TARGET from host, and check the source IP of captured packets

```
ping -i IP1 TARGET  ==> got IP1. correct
ping -i IP2 TARGET ==> got IP2. correct
```

7. "ping TARGET" inside SERVER1, check the source IP of captured packets. It is IP1, correct.

8. "ping TARGET" inside SERVER2

9. Check the source IP of captured packets (it is still IP1, not as expected).

**Output of `docker version`:**

```
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:10:06 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:08:35 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**

```
Containers: 24
 Running: 10
 Paused: 0
 Stopped: 14
Images: 284
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-6-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.714GiB
Name: docker
ID: FIHD:YWUO:OTRU:44RI:UGUF:4VQW:473Z:4VZ3:OZTY:ZXJP:2OTQ:ZUB6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
