### ISSUE TITLE
Unexpected behavior: docker-containerd listen to tcp port 10010 "externally"

### ISSUE THREAD

**Issue by yw662** [docker/for-linux#405]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
docker-containerd should not listen to any ports externally. It should be 127.0.0.1 by default, which might be configured to sth. else.

### Actual behavior
docker-containerd listen to tcp port <external ip address>:10010.
And, surprisingly it is not 127.0.0.1:10010 or 0.0.0.0:10010.

### Steps to reproduce the behavior
Just start docker daemon, and `ss -tnlp`, or `ss -tlp|grep 10010`.

**Output of `docker version`:**

```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:09:54 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:07:56 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-20-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

not relevant.

**Comment by yw662** [comment]
and the roml file, if you really want to know. It is just the default one (at least for ubuntu 18.04).

```toml
root = "/var/lib/docker/containerd/daemon"
state = "/var/run/docker/containerd/daemon"
oom_score = -500

[grpc]
  address = "/var/run/docker/containerd/docker-containerd.sock"
  uid = 0
  gid = 0
  max_recv_message_size = 16777216
  max_send_message_size = 16777216

[debug]
  address = "/var/run/docker/containerd/docker-containerd-debug.sock"
  uid = 0
  gid = 0
  level = "info"

[metrics]
  address = ""
  grpc_histogram = false

[cgroup]
  path = ""

[plugins]
  [plugins.linux]
    shim = "docker-containerd-shim"
    runtime = "docker-runc"
    runtime_root = "/var/lib/docker/runc"
    no_shim = false
    shim_debug = false
````
