### ISSUE TITLE
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### ISSUE THREAD

**Issue by joergklein** [docker/for-linux#489]
I wrote a .gitlab-ci.yml to install docker ce. But I can not start docker. The docker daemon is not in /var/run. I get this error message:

```
$ id -nG
root
$ usermod -aG docker root
$ ls -la /var/run/*
-rw-rw-r--. 1 root utmp    0 Oct 18 21:02 /var/run/utmp

/var/run/lock:
total 16
drwxrwxrwt. 2 root root 4096 Oct 18 21:02 .
drwxr-xr-x. 1 root root 4096 Oct 19 00:47 ..

/var/run/mount:
total 20
drwxr-xr-x. 2 root root 4096 Oct 18 21:02 .
drwxr-xr-x. 1 root root 4096 Oct 19 00:47 ..
-rw-r--r--. 1 root root    0 Oct 18 21:02 utab

/var/run/systemd:
total 24
drwxr-xr-x. 2 root root 4096 Oct 19 00:47 .
drwxr-xr-x. 1 root root 4096 Oct 19 00:47 ..
-rw-r--r--. 1 root root    7 Oct 19 00:47 container
$ docker info
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
ERROR: Job failed: exit code 1

```
here the gitlab-ci.yml

```
image: ubuntu:latest

before_script:
  - apt-get update
  - apt-get install -y apt-transport-https ca-certificates curl software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add
  - apt-key fingerprint 0EBFCD88
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update

stages:
    - test

test:
  stage: test
  script:
    - apt-get install -y docker-ce
    - id -nG
    - usermod -aG docker root
    - ls -la /var/run/*
    - docker info
    - service docker status
    - service docker start
    - service docker status
    - docker run hello-world

```
