### ISSUE TITLE
is get-started 4 in document broken? connection refused even port is right

### ISSUE THREAD

**Issue by NewUserHa** [docker/for-linux#508]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

docker-ce 18.9

I followed everthing in  https://docs.docker.com/get-started/part4/ and used the compose.yml in the doc and replace the app image with `/bibekmantree/friendlyhello/` as blow
```
version: "3"
services:
  web:
    image: /bibekmantree/friendlyhello/
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "80:80"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "/home/docker/data:/data"
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - webnet
networks:
  webnet:
```

none of them can be accessd from the `host machine`, not in the `myvm1`

`curl http://192.168.99.100:8080` return `curl ..error [7] ...connection refused...`
even `docker-machine ssh myvm1 "curl http://127.0.0.1:8080"` return `curl ..error [7] ...connection refused...`

two vms' ip are 192.168.99.100 and 192.168.99.101

I already checked evething using docker inspect. and there is port listening using `ss -l` in myvm1
I spent 5 housr! how could this be possible??

Thanks
