### ISSUE TITLE
Docker container not responding to anything

### ISSUE THREAD

**Issue by Prince269090** [docker/for-linux#515]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior

Docker container should run smoothly.

### Actual behavior

Sometimes docker containers in the system not responds to anything and if we try to access it will always show up and running. 

### Steps to reproduce the behavior

1. Create a custom image with node:10.11.0 as a base image and any sample node project which listens on port 4000.
```
#Step 1.
FROM node:10.11.0

#Step 2
LABEL version="1.0"

#Step 3.
RUN mkdir -p /usr/src/core-api
WORKDIR /usr/src/core-api

#Step 4.
COPY package*.json ./
COPY tsconfig*.json ./
COPY tslint*.json ./

#Step 6..
RUN npm install pm2 -g

#Step 7
RUN cd /usr/src/core-api && npm install --production

#Step 8
COPY ./dist ./dist

#Step 9.
EXPOSE 4000

#Step 10.
CMD npm run start-docker
```
2. Push the custom image image to the repository.

3. Run the image with docker compose. 
```
version: '2'
services:
  core:
    image: libsynadmin/libsynmp:core-api-staging-0.6.0.1
    restart: always
    volumes:
      - /home/rspurohit/core-api/public/podcast-images:/usr/src/core-api/dist/libsyn-mp.core/src/public/podcast-images
      - /home/rspurohit/core-api/public/campaign-documents:/usr/src/core-api/dist/libsyn-mp.core/src/public/campaign-documents
      - /home/rspurohit/core-api/public/network-images:/usr/src/core-api/dist/libsyn-mp.core/src/public/network-images
      - /home/rspurohit/core-api/public/user-profile-images:/usr/src/core-api/dist/libsyn-mp.core/src/public/user-profile-images
      - /home/rspurohit/core-api/public/smart-proposals:/usr/src/core-api/dist/libsyn-mp.core/src/public/smart-proposals
      - /home/rspurohit/core-api/public/insertion-orders:/usr/src/core-api/dist/libsyn-mp.core/src/public/insertion-orders
      - /home/rspurohit/core-api/public/invoice:/usr/src/core-api/dist/libsyn-mp.core/src/public/invoice
      - /home/rspurohit/core-api/public/payslip:/usr/src/core-api/dist/libsyn-mp.core/src/public/payslip
    ports:
      - '4000:4000'
      - '3000:3000'
    network_mode: bridge
    environment:
      - NODE_ENV=development-local
```
4. Container will be up and running but sometimes it stops reponding and we don't get any output from if we hit the url http://loalhost:4000. Eventhough container and docker are up and running.

5. There are 5 containers running in my system with same above configuration but different services and all of them stops responding at the same time.

6. Once i restart the docker service everything starts working noraml.

**Output of `docker version`:**
```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 6
 Running: 5
 Paused: 0
 Stopped: 1
Images: 13
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-128-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.702GiB
Name: lsyn-bgqa
ID: RFOD:4VQN:N4DY:IBTV:FADZ:V6CW:6ZMB:FJL2:365D:43FI:WKNP:MI5W
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: libsynadmin
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

It is a VM created with below details.

NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
