### ISSUE TITLE
Macvlan connection errors

### ISSUE THREAD

**Issue by strowi** [docker/for-linux#583]
* [x] This is a bug report

### Expected behavior
Multiple Containers on same host using macvlan network being able to:
- connect to the "outside" 
- connect to backend services
-(consistent behaviour)

### Actual behavior
- inconsistent behaviour, some containers are able to connect to backend, others not

### Steps to reproduce the behavior
1. create macvlan network:
```
~@> docker network create -d macvlan --subnet=185.xx.yy.0/26 --gateway=185.xx.yy.1 -o parent=bond0.2000 --attachable public
```

2. deploy following docker-compose.yml:
```
version: '2.2'

services:
  haproxy:
    image: hub.domain.net/sys/docker/ttrss/haproxy:latest
    restart: always
    depends_on:
    - ttrss
    volumes:
    - ./src/ssl:/etc/haproxy/ssl:ro
    networks:
      public1:
        ipv4_address: 185.xx.yy.30
      default:

  ttrss:
    image: hub.domain.net/sys/docker/ttrss/ttrss:latest
    restart: always
    networks:
      - default
    environment:
      - TTRSS_SELF_URL=http://rss.domain.net/
      - SELF_URL_PATH=http://rss.domain.net/
      - TTRSS_PORT=8080
      - DB_PORT_3306_TCP_ADDR=lb.prod2-r.domain.net
      - DB_PORT_3306_TCP_PORT=3306
      - DB_TYPE=mysql
      - DB_HOST=lb.prod2-r.domain.net
      - DB_PORT=3306
      - DB_NAME=ttrss
      - DB_USER=ttrss
      - DB_PASS=pass
    volumes:
      - ttrss2:/var/www

networks:
  public1:
    external:
      name: public


volumes:
  ttrss2:
```
-> everything works as expected, i can browse to rss.domain.net, i get the backend response.

Now deploy the same with different IP (.27) from another folder..

```
~> sudo docker network inspect public
[
    {
        "Name": "public",
        "Id": "dbdb1bedc58f0beb308dbcce5f3fe738f6aec75e10e91d5a69ad56e51b911f3c",
        "Created": "2019-02-06T11:47:00.20158789+01:00",
        "Scope": "local",
        "Driver": "macvlan",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "185.xx.yy.0/26",
                    "Gateway": "185.xx.yy.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "206f3a2ccbfaedf245267e47923ed11409164ccdb45229fb08e4aadb61582052": {
                "Name": "ttrss_haproxy_1",
                "EndpointID": "15b2d9963916986779bbb2903185274f3892740a67d5763352d207522c1a14b5",
                "MacAddress": "02:42:b9:0d:d0:1e",
                "IPv4Address": "185.xx.yy.30/26",
                "IPv6Address": ""
            },
            "25fe1397031e0f0faf0ba965b3a64665ce50ed0ddf5d21ad6d32880ee2196409": {
                "Name": "ttrss2_haproxy_1",
                "EndpointID": "d93a6d5425192bc4dcab35e528cd88b335dbdd08089033214db3713a51b7bb8a",
                "MacAddress": "02:42:b9:0d:d0:1b",
                "IPv4Address": "185.xx.yy.27/26",
                "IPv6Address": ""
            },
            "9f3831dab7dbea84de44774495a57b8bb64c79eac0599368a96d00a856fe03f8": {
                "Name": "mailrelay_mailrelay-fra_1",
                "EndpointID": "1b1a7edcbb54dcdd9bd39fd86f5f0b3bb19e13a97ed4e04be12072d9d55ba4bd",
                "MacAddress": "02:42:b9:0d:d0:32",
                "IPv4Address": "185.xx.yy.50/26",
                "IPv6Address": ""
            }
        },
        "Options": {
            "parent": "bond0.2000"
        },
        "Labels": {}
    }
]
```

Container 
- ttrss_haproxy_1 ( 185.xx.yy.30) is reachable from the outside, 
- ttrss2_haproxy_1 (185.xx.yy.27) is not.

**Output of `docker version`:**

```
~$ sudo docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:51 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:15 2018
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Output of `docker info`:**

```
~$ sudo docker info
Containers: 12
 Running: 9
 Paused: 0
 Stopped: 3
Images: 14
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-45-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 62.88GiB
Name: ranch15
ID: UBHS:BK63:5QOP:6W6K:PANL:ETVI:PHCI:CSBR:A3JZ:Q2V6:EDM4:N54X
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false(paste your output here)
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
- bare-Metal, bonded eth0+eth1
- vlan 2000 on bond0.2000 routes 185.xx.yy.0/24

regards,
strowi
