### ISSUE TITLE
rm: cannot remove ‘folder’: Device or resource busy docker

### ISSUE THREAD

**Issue by ghost** [docker/for-linux#649]
I had a local folder as volume bind mount, then commited my image, then I removed the volume mount. Now the folder is still there (but empty) and refuses to delete. I tried:
```
$ docker exec -it --privileged --user root f105b6bfec00 rm -R Desktop/app
$ rm: cannot remove ‘Desktop/app’: Device or resource busy

$ docker exec -it --privileged --user root f105b6bfec00 lsof +D Desktop/app
$ 
```
This is the docker-compose file and image, the folder is still part of the image and no idea how to remove it (Desktop/app):
```
version: '2'
services:
  centos-vnc-node: 
    image: davedm/centos-node-chrome-vnc:latest
    volumes:
      - .:/headless/Desktop/app
    ports:
      - 6901:6901
      - 5901:5901   
    environment:
      - VNC_PW=password12345678
```
