### ISSUE TITLE
Unable to determine replica hostname in container

### ISSUE THREAD

**Issue by kallisti5** [docker/for-linux#707]
From within docker containers (deployed to swarm mode, via docker-compose), it doesn't seem possible to determine the replica hostname.

As an example, I can address three containers as follows:

* etcd.1
* etcd.2
* etcd.3

However, within each of these containers, the replica id / name isn't known. The only thing presented to the user is the randomly generated hostname (which is fine in some situations, not in others)

It would be nice in addition to the randomly generated, if a new environment variable was injected.

* HOSTNAME_DOCKER="etcd.1"
* DOCKER_REPLICA_ID="1"
* etc.

*OR* make this information available within the docker-compose?

Example:
If users had access to the friendly hostname, they could deploy things like etcd and have a cluster form automatically without using SRV records.

```
version: "3.2"
services:
  etcd:
    image: quay.io/coreos/etcd:latest
    command: "etcd --name=**etcd.1** --initial-cluster=http://etcd.1:2380,http://etcd.2:2380,default=http://etcd.3:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=ingress-cluster-1
    deploy:
      replicas: 3
      placement:
        constraints: [node.role==manager]
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - sysadmin
```
