### ISSUE TITLE
Docker Overlay network works on play-with-docker but not in ubuntu 16.04!

### ISSUE THREAD

**Issue by julianfrank** [docker/for-linux#98]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behaviour
The Container Services should get exposed on 9000 and 8080 

### Actual behavior
They don't on Ubuntu 16.04/Docker version 17.06.2-ce, build cec0b72 :(

### Steps to reproduce the behavior
 Use this docker stack yml
``` yaml
version: "3.1"
networks:
  webnet:
services:
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - webnet
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - webnet
```
Run it using the command 
``` bash
docker stack deploy -c <filename>.yml infra
```
**Output of `docker version`:**
```
Docker version 17.06.2-ce, build cec0b72

```

**Output of `docker info`:**
```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 103
Server Version: 17.06.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 114
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: z0lydjuhd7o7fw568mrrd63oi
 Is Manager: true
 ClusterID: v748477wx9l8u6fzb92vmd98t
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 127.0.1.1
 Manager Addresses:
  127.0.1.1:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-33-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 14.62GiB
Name: jfubuntu
ID: 5AVR:R3RE:5LFV:CULR:SD4A:55FX:UKGR:XI3K:NWRB:Z4AS:KBUM:2MAT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

Its a local direct Ubuntu Install... This used to work three weeks back but only tried today and strangely not working ... Its works perfectly fine on pay-with-docker even now...
